name: CI/CD Pipeline

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    - name: Build Docker Image
      run: docker build -t stock-ticker .

    - name: Push Docker Image to Registry
      run: docker push your-docker-repo/stock-ticker:latest