name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set Up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean compile

      # Step 4: Run Tests
      - name: Run tests with Maven
        run: mvn test

      # Step 5: Package Application
      - name: Package with Maven
        run: mvn package

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/stock-ticker .

      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push kaspermaukkonen/stock-ticker:latest